version: '2'
services:
  manytomany-app:
    image: manytomany
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://manytomany-postgresql:5432/manytomany
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://manytomany-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://manytomany-elasticsearch:9200
  manytomany-postgresql:
    extends:
      file: postgresql.yml
      service: manytomany-postgresql
  manytomany-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: manytomany-elasticsearch
